language: php
php:
  
  - '7.1'
  
services: 
  - 'mongodb'
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e 'create database homestead_test';

script:
  # - vendor/bin/phpunit