language: php
php:
  - '5.4'
  - '6.5'
  - '7.1'
  - '7.2'
  - '7.3'
  
services: 
  - 'mongodb'
  - 'mysql'
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e 'create database homestead_test';
  

script: "Check Script"
  - 'php artisan passport:install'
  - 'php artisan config:cache'

os:
  - "linux"
  - "windows"
  